apiVersion: v1
kind: PersistentVolume
metadata:
  name: nagios-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: C:\data\nagios
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nagios-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
